### ISSUE TITLE
Incompatibility with vis-network sortMethod

### ISSUE THREAD

**Issue by Maroe-C** [delcourtfl/vis-network-moving-nodes-on-edges#1]
Hello,

Thank you very much for your work. It has been very useful for the task I'm working on. 

However, I require using a vis-network specific option : 
I need to sort hierarchically my nodes thanks to the "directed" sort method. 
When doing this combined with your animation feature, the tree is displaced to the left each time I press down the "try it" button. 

Is there a way to solve this problem?

**Comment by delcourtfl** [comment]
Hello,

Sadly I didn't find an easy way to exclude the moving nodes from the LayoutEngine like it is done for the PhysicsEngine. 

For now I think that the best workaround is to load the network with the proper layout and disable the LayoutEngine once the nodes are placed to avoid the recalculation each time a temporary node is added/removed (but if you want to modify the layout of the main network later on, you will need to set the option each time).

I hope this is enough to solve your issue.

```javascript

var options = {
    "physics": {
        "enabled": false,
    },
    "layout": {
      "hierarchical": {
        "enabled": true,
        "direction": "UD",
        "sortMethod": "directed",
      },
    },
};
var network = new vis.Network(container, data, options);

// Disable the layout engine once the nodes are in place
network.layoutEngine.options.hierarchical.enabled = false;

```

**Comment by Maroe-C** [comment]
It works, thanks !
